CREATE TABLE epsdlp.fact_gl_transactions
(
 `accrual_type` string,
 `accrued_by_user` string,
 `accrued_by_user_2` string,
 `accrued_on_date` timestamp,
 `allocation_date_from` timestamp,
 `allocation_date_to` timestamp,
 `amount` decimal(38,18),
 `application_code` string,
 `application_ref` string,
 `approval_level` string,
 `approved_by` string,
 `ar_type` string,
 `bank` string,
 `book_credit_off` decimal(38,18),
 `book_debit_off` decimal(38,18),
 `book_value` decimal(38,18),
 `book_value_off` decimal(38,18),
 `book_value2` decimal(38,18),
 `book_value3` decimal(38,18),
 `budget` string,
 `bunker_price` decimal(38,18),
 `bunker_qty` decimal(38,18),
 `created_by_user` string,
 `created_by_user_2` string,
 `currency` string,
 `currency3` string,
 `db_userid` string,
 `debit_credit` string,
 `document_category` string,
 `document_date` timestamp,
 `document_status` string,
 `document_subject` string,
 `document_subsubject` string,
 `document_type` string,
 `due_date` timestamp,
 `entry_number` decimal(38,18),
 `entry_rate` decimal(38,18),
 `entry_rate2` decimal(38,18),
 `entry_rate3` decimal(38,18),
 `filed_to` string,
 `filed_to3` string,
 `finalized_by_user` string,
 `finalized_by_user_2` string,
 `flag1` string,
 `flag2` string,
 `flag3` string,
 `from_to` string,
 `fx_rate` decimal(38,18),
 `import_status` string,
 `imported_by` string,
 `inc_exp_category` string,
 `inc_exp_group` string,
 `instrument_no` string,
 `issue_date` timestamp,
 `job_number` string,
 `journal_company` string,
 `journal_date` timestamp,
 `journal_line` decimal(38,18),
 `journal_number` string,
 `journal_posting` timestamp,
 `journal_series` string,
 `journal_status` string,
 `journal_user` string,
 `journal_user_2` string,
 `last_updated` timestamp,
 `matching_company` string,
 `matching_line` decimal(38,18),
 `matching_number` string,
 `matching_series` string,
 `mc_reference` string,
 `name` string,
 `open_item_status` string,
 `operation_code1` string,
 `operation_code2` string,
 `operation_id1` string,
 `operation_id2` string,
 `operation_subid_1` string,
 `operation_subid_2` string,
 `order_number` string,
 `our_company` string,
 `pay_approval_level` decimal(38,18),
 `pay_flag` string,
 `pay_selected` string,
 `payment_method` string,
 `place` string,
 `prt_flag` string,
 `remarks` string,
 `reporting_amount` decimal(38,18),
 `serial_no` string,
 `set_currency_amount` decimal(38,18),
 `spot_rate_flag` string,
 `sup_match` string,
 `supplier_code` string,
 `team` string,
 `tot_book_credit` decimal(38,18),
 `tot_book_credit2` decimal(38,18),
 `tot_book_credit3` decimal(38,18),
 `tot_book_debit` decimal(38,18),
 `tot_book_debit2` decimal(38,18),
 `tot_book_debit3` decimal(38,18),
 `tot_local_credit` decimal(38,18),
 `tot_local_debit` decimal(38,18),
 `transaction_type` string,
 `vat_amount` decimal(38,18),
 `vat_category` string,
 `vat_number` string,
 `vessel_code` string,
 `withholding_tax_amount` decimal(38,18),
 `withholding_tax_code` string,
 `journal_narrative` string,
 `journal_reference` string,
 `flag4` string,
 `submission_date` timestamp,
 `value_date` timestamp,
 `transaction_cost` string,
 `accrual_flag` decimal(38,18),
 `order_code` string,
 `document_code` string,
 `internal_ref` string,
 `row_num` bigint,
 `account_id` string,
 `company_id` string,
 `vessel_id` string,
 `service_id` string,
 `department_id` string,
 `intercompany_id` string,
 `future1_id` string,
 `future2_id` string,
 `code_combination_id` string,
 `journal_id` string,
 `tot_global_credit` decimal(38,18),
 `tot_global_debit` decimal(38,18),
 `delete_flag` int,
 `integration_key` string,
 `w_x_custom` string,
 `w_job_instance_id` bigint ,
 `w_refresh_ts` timestamp ,
 `w_curr_rec_flg` string,
 `w_data_src_id` string,
 `w_location` string ,
 `w_batch_id` bigint ,
 `business_date` timestamp) using delta
 PARTITIONED BY  (
 `business_date`
) LOCATION '/mnt/epsdldeltaprod/epsdlp/fact_gl_transactions' TBLPROPERTIES ('transactional'='false');


CREATE TABLE epsdlp.fact_gl_budget
(
 `vessel_code` string,
 `matching_date` date,
 `ledger_card` string,
 `tot_book_debit` decimal(38,18),
 `tot_book_credit` decimal(38,18),
 `year` int,
 `vessel_id` string,
 `company_id` string,
 `account_id` string,
 `reporting_lines_id` string,
 `integration_key` string,
 `w_x_custom` string,
 `w_job_instance_id` bigint ,
 `w_refresh_ts` timestamp ,
 `w_curr_rec_flg` string,
 `w_data_src_id` string,
 `w_location` string ,
 `w_batch_id` bigint ,
 `business_date` timestamp) using delta
 PARTITIONED BY  (
 `business_date`
) LOCATION '/mnt/epsdldeltaprod/epsdlp/fact_gl_budget' TBLPROPERTIES ('transactional'='false');


CREATE TABLE epsdlp.fact_dry_dock_details
(
 `vessel_code` string ,
 `vessel_id` string ,
 `dd_days` timestamp ,
 `dt_actual_entry` timestamp ,
 `dt_actual_exit` timestamp ,
 `dt_planned_entry` timestamp ,
 `dt_planned_exit` timestamp,
 `matching_date` date,
 `w_batch_id` bigint ,
 `business_date` timestamp ,
 `w_data_src_id` string ,
 `w_refresh_ts` timestamp ,
 `w_x_custom` string,
 `w_job_instance_id` bigint ,
 `w_curr_rec_flg` string,
 `w_location` string,
 `integration_key` string
)
using delta
 PARTITIONED BY  (
 `business_date`
) LOCATION '/mnt/epsdldeltaprod/epsdlp/fact_dry_dock_details' TBLPROPERTIES ('transactional'='false');


CREATE TABLE epsdlp.fact_ship_days
(
 `vessel_code` string ,
 `vessel_id` string ,
 `full_date` date,
 `start_date` date,
 `sold_date` date,
 `ship_days` int,
 `w_batch_id` bigint ,
 `business_date` timestamp ,
 `w_data_src_id` string ,
 `w_refresh_ts` timestamp ,
 `w_x_custom` string,
 `w_job_instance_id` bigint ,
 `w_curr_rec_flg` string,
 `w_location` string,
 `integration_key` string
)
using delta
 PARTITIONED BY  (
 `business_date`
) LOCATION '/mnt/epsdldeltaprod/epsdlp/fact_ship_days' TBLPROPERTIES ('transactional'='false');


CREATE TABLE epsdlp.fact_os_po
(
 `parcial` decimal(38,18),
 `order_qty` decimal(38,18),
 `invoice_qty` decimal(38,18), 
 `order_price` decimal(38,18),
 `order_rate` decimal(38,18),
 `order_discount` decimal(38,18),
 `invoice_price` decimal(38,18),
 `invoice_rate` decimal(38,18),
 `invoice_discount` decimal(38,18),
 `acc_code` string,
 `acrl_code` string,
 `comments` string,
 `document_date` timestamp,
 `order_currency` string,
 `order_code` string,
 `accounts_team` string,
 `business_team` string,
 `vessel_code` string, 
 `vessel_id` string,
 `vessel_name` string,
 `department` string,
 `item_system_code` string,
 `item_subsystem_code` string,
 `ledger_card` string,
 `order_supplier` string,
 `order_date` timestamp,
 `disputed_date` timestamp,
 `disputed_comments` string,
 `approver` string,
 `requested_qty` decimal(38,18),
 `approved_qty` decimal(38,18),
 `item_serial_no` decimal(38,18),
 `item_ref_code` string,
 `delivery_date` timestamp,
 `vessel_code1` string, 
 `vessel_name1` string,
 `dd_po_flag` string,
 `dd_po_flag_cy` string,
 `approver_po_flag` string,
 `account_id` string, 
 `item_amount_po_usd` decimal(38,18),
 `document_code` string,
 `line_type` string,
 `vessel_current_year_flag` string,
 `order_code_line_type` string,
 `w_data_src_id` string ,
 `w_job_instance_id` bigint ,
 `w_curr_rec_flg` string,
 `w_x_custom` string,
 `w_refresh_ts` timestamp ,
 `w_location` string ,
 `w_batch_id` bigint ,
 `business_date` timestamp) using delta
 PARTITIONED BY  (
 `business_date`
) LOCATION '/mnt/epsdldeltaprod/epsdlp/fact_os_po' TBLPROPERTIES ('transactional'='false');
