api_url: https://epsdlguzzlevm-2d89c68b94.southeastasia.cloudapp.azure.com:9090
context_columns:
- system
- location
database:
  properties:
    jdbc_url: jdbc:sqlserver://epsdlsqlserver.database.windows.net;database=epsdlsqlserverdbguzzlemeta;encrypt=true;trustServerCertificate=true;create=false;loginTimeout=30;socketKeepAlive=true
    password: '{ENC}YBYBTd+l3rZ0GJZBHyRV3g=='
    username: epsdladmin
  type: jdbc
default_spark: guzzle_databricks_cluster
java:
  classpath: ''
module_mapping:
  atlas_plugin:
    class_name: com.justanalytics.guzzle.plugin.atlas.Main
    jar_name: atlas-plugin.jar
  constraint_checks:
    class_name: com.justanalytics.guzzle.dq.Main
    jar_name: dq.jar
  data-sampling:
    class_name: com.justanalytics.guzzle.datasampling.Main
    jar_name: data-sampling.jar
  external:
    class_name: com.justanalytics.guzzle.external.Main
    jar_name: external.jar
  housekeeping:
    class_name: com.justanalytics.guzzle.housekeeping.Main
    jar_name: housekeeping.jar
  ingestion:
    class_name: com.justanalytics.guzzle.ingestion.Main
    jar_name: ingestion.jar
  orchestration:
    class_name: com.justanalytics.guzzle.orchestration.Main
    initializer_class: com.justanalytics.guzzle.orchestration.BatchInitializer
    jar_name: orchestration.jar
    job_executor_class: com.justanalytics.guzzle.orchestration.ExecuteJob
  processing:
    class_name: com.justanalytics.guzzle.processing.Main
    jar_name: processing.jar
  recon:
    class_name: com.justanalytics.guzzle.recon.Main
    jar_name: recon.jar
stages:
- STG
- FND
- PLP
version: 1
