version: 1
job:
  type: "processing"
  tags:
  - "epsdl_dim"
source:
  endpoint: "lo_delta_tables"
  properties:
    sql: "select \nuser_email\n,company_codes\n,vessel_codes\n,integration_key\n,null as w_x_custom\n,w_job_instance_id\n,w_refresh_ts\n,null as w_curr_rec_flg\n,w_source_system as w_data_src_id\n,w_location\n,w_batch_id\n,'${business_date}' as business_date\nfrom ${p_epsdl_sri_db}.sri_data_security\nwhere w_business_dt='${business_date}'"
  additional_columns:
  - name: "w_refresh_ts"
    value: "current_timestamp"
  - name: "business_date"
    value: "'${business_date}'"
  - name: "w_job_instance_id"
    value: "${job_instance_id}"
  - name: "w_batch_id"
    value: "${batch_id}"
  - name: "w_location"
    value: "'ALL'"
  - name: "w_source_system"
    value: "'MANUAL'"
target:
  operation: "append"
  properties:
    template: "default"
    table: "${p_epsdl_db}.dim_data_security"
  endpoint: "lo_delta_tables"
