description: ""
version: 1
properties: {}
jobs:
- "sri_del_departments"
- "sri_supply_items"
- "sri_requisitions"
- "sri_order_details"
- "sri_dept_mapping"
- "sri_supplier_invoicing"
- "sri_delivery_point"
- "sri_supplier_registry"
- "sri_reqn_audit_log"
parallel: 5
