description: ""
version: 1
properties: {}
jobs:
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_period"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_os_po"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_gl_transactions"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_gl_account"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_gl_company"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_gl_reporting_lines"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_gl_budget"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_gl_service"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_gl_vessel"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_ship_days"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_dry_dock_details"
- "synapse_rej_sri_account_mapping"
- "synapse_rej_sri_budget_opex_monitor"
- "synapse_rej_sri_company_hierarchy"
- "synapse_rej_sri_company_master"
- "synapse_rej_sri_del_departments"
- "synapse_rej_sri_dept_mapping"
- "synapse_rej_sri_documents"
- "synapse_rej_sri_expected_call_da"
- "synapse_rej_sri_item_ledgers"
- "synapse_rej_sri_order_details"
- "synapse_rej_sri_reporting_lines"
- "synapse_rej_sri_requisitions"
- "synapse_rej_sri_service_hierarchy"
- "synapse_rej_sri_supply_items"
- "synapse_rej_sri_vessel_dry_dock_details"
- "synapse_rej_sri_vessel_hierarchy"
- "synapse_rej_sri_vessel_team_map"
- "synapse_rej_sri_vessel_master"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_department"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_requisitions"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_reqn_audit"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_requisitions_category"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "dim_supplier"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_supply_items"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_supplier_invoicing"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_requisitions_category"
- "synapse_rej_sri_supplier_invoicing"
- "synapse_rej_sri_reqn_audit_log"
- "synapse_rej_sri_supplier_registry"
- "synapse_rej_sri_delivery_point"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_gl_balance"
- plp_adls_synapse:
    job_parameters:
      p_table_name: "fact_port_calls_master"
- "synapse_rej_sri_bp_ports"
- "synapse_rej_sri_expected_call"
- "synapse_rej_sri_imos_expected_call"
- "synapse_rej_sri_imos_port_call"
- "synapse_rej_sri_ports_library"
- "synapse_rej_sri_telegrams"
- "synapse_rej_sri_telegrams_custom"
parallel: 4
