CREATE TABLE epsdld.fact_supply_items
(
`document_code` string,
`item_serial_no` decimal(38,18),
`invoice_code` string,
`parcial` decimal(38,18),
`order_price` decimal(38,18),
`order_qty` decimal(38,18),
`order_rate` decimal(38,18),
`order_discount` decimal(38,18),
`invoice_price` decimal(38,18),
`invoice_qty` decimal(38,18),
`invoice_rate` decimal(38,18),
`invoice_discount` decimal(38,18),
`item_short_desc` string,
`order_currency` string,
`order_code` string,
`vessel_code` string,
`department` string,
`document_no` decimal(38,18),
`line_type` string,
`order_supplier` string,
`document_date` timestamp,
`comments` string,
`requisition_code` string,
`delivery_date` timestamp,
`delivery_port` string,
`po_description` string,
`department_id` string,
`vessel_id` string,
`supplier_id` string,
`requisition_id` string,
`integration_key` string,
`w_batch_id` double ,
`business_date` timestamp ,
`w_data_src_id` string ,
`w_refresh_ts` timestamp ,
`w_x_custom` string,
`w_job_instance_id` bigint ,
`w_curr_rec_flg` string,
`w_location` string) using delta
PARTITIONED BY  (
`business_date`
) LOCATION '/mnt/epsdldeltadev/epsdld/fact_supply_items' TBLPROPERTIES ('transactional'='false');


CREATE TABLE epsdld.fact_supplier_invoicing
(
`document_code` string,
`item_serial_no` decimal(38,18),
`invoice_code` string,
`parcial` decimal(38,18),
`order_price` decimal(38,18),
`order_qty` decimal(38,18),
`order_rate` decimal(38,18),
`order_discount` decimal(38,18),
`invoice_price` decimal(38,18),
`invoice_qty` decimal(38,18),
`invoice_rate` decimal(38,18),
`invoice_discount` decimal(38,18),
`item_short_desc` string,
`order_currency` string,
`invoice_amount` double,
`addn_packing_cost` double,
`addn_forwarding_cost` double,
`supplier_invoice_discount` double,
`status` double,
`currency` string,
`invoice_no` string,
`invoice_date` timestamp,
`order_code` string,
`vessel_code` string,
`department` string,
`document_no` decimal(38,18),
`line_type` string,
`order_supplier` string,
`document_date` timestamp,
`comments` string,
`requisition_code` string,
`delivery_date` timestamp,
`delivery_port` string,
`po_description` string,
`department_id` string,
`vessel_id` string,
`supplier_id` string,
`requisition_id` string,
`integration_key` string,
`w_batch_id` double ,
`business_date` timestamp ,
`w_data_src_id` string ,
`w_refresh_ts` timestamp ,
`w_x_custom` string,
`w_job_instance_id` bigint ,
`w_curr_rec_flg` string,
`w_location` string) using delta
PARTITIONED BY  (
`business_date`
) LOCATION '/mnt/epsdldeltadev/epsdld/fact_supplier_invoicing' TBLPROPERTIES ('transactional'='false');


CREATE TABLE epsdld.fact_requisitions_category
(
`amount_usd_po` decimal(38,18),
`line_type` string,
`order_date` timestamp,
`order_currency` string,
`document_date` timestamp,
`department_id` string,
`vessel_id` string,
`department` string,
`dept_name` string,
`document_code` string,
`order_code` string,
`requisition_code` string,
`rfq_supplier_name` string,
`vessel_code` string,
`vessel_name` string,
`req_desc` string,
`date_sent_to_office` timestamp,
`audit_date` timestamp,
`integration_key` string,
`w_batch_id` double ,
`business_date` timestamp ,
`w_data_src_id` string ,
`w_refresh_ts` timestamp ,
`w_x_custom` string,
`w_job_instance_id` bigint ,
`w_curr_rec_flg` string,
`w_location` string) using delta
PARTITIONED BY  (
`business_date`
) LOCATION '/mnt/epsdldeltadev/epsdld/fact_requisitions_category' TBLPROPERTIES ('transactional'='false');



